[project]
name = "qr-map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "jupyterlab>=4.4.9",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
]
